# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wPSpt_aGysvnoVEIuoSJVnsGiPtrErP_
"""

# 11. Build Dictionary from Two Lists
# --------------------------------------------------
def build_dictionary(keys, values):
    result = {}

    for i in range(len(keys)):
        result[keys[i]] = values[i]

    return result


print("\nDictionary Tests:")
print(build_dictionary(["a", "b", "c"], [1, 2, 3]))
print(build_dictionary(["name", "age"], ["John", 25]))

# 12. Count Vowels in a String
# --------------------------------------------------
def count_vowels(text):
    vowels = "aeiouAEIOU"
    count = 0

    for char in text:
        if char in vowels:
            count += 1

    return count


print("\nVowel Count Tests:")
print(count_vowels("Python"))
print(count_vowels("Education"))

# 13. Celsius <-> Fahrenheit Converter
# --------------------------------------------------
def celsius_to_fahrenheit(celsius):
    return (celsius * 9 / 5) + 32


def fahrenheit_to_celsius(fahrenheit):
    return (fahrenheit - 32) * 5 / 9


print("\nTemperature Conversion Tests:")
print(celsius_to_fahrenheit(0))
print(celsius_to_fahrenheit(100))
print(fahrenheit_to_celsius(32))
print(fahrenheit_to_celsius(212))

# 14. Grade Calculator
# --------------------------------------------------
def calculate_grade(score):
    if score >= 90:
        return "A"
    elif score >= 80:
        return "B"
    elif score >= 70:
        return "C"
    elif score >= 60:
        return "D"
    else:
        return "F"


print("\nGrade Calculator Tests:")
print(calculate_grade(95))
print(calculate_grade(72))

# 15. Simple Calculator
# --------------------------------------------------
def calculator(num1, num2, operator):

    if operator == "+":
        return num1 + num2

    elif operator == "-":
        return num1 - num2

    elif operator == "*":
        return num1 * num2

    elif operator == "/":
        if num2 == 0:
            return "Error: Division by zero"
        return num1 / num2

    else:
        return "Invalid Operator"


print("\nCalculator Tests:")
print(calculator(10, 5, "+"))
print(calculator(10, 5, "/"))
print(calculator(10, 0, "/"))